export const FIELD_TYPES = {
  text: "text",
  textarea: "textarea",
  select: "select",
  checkbox: "checkbox",
  date: "date",
  email: "email",
  tel: "tel",
  divider: "divider",
  header: "header",
  staticText: "staticText",
  bannerImage: "bannerImage",
  signature: "signature",
  radioGroup: "radioGroup",
  externalLink: "externalLink",
  infoDialog: "infoDialog",
  minorVolunteers: "minorVolunteers",
  whoAreYou: "whoAreYou",
  dayOfService: "dayOfService",
};
