import { FIELD_TYPES } from "./FieldTypes";

export const AVAILABLE_FIELDS = {
  firstName: {
    label: "First Name",
    type: FIELD_TYPES.text,
    visible: true,
    required: true,
    originalLabel: "First Name",
    validation: (value) =>
      value.length >= 2 ? null : "First name must be at least 2 characters",
    helpText: "Enter your legal first name as it appears on official documents",
    category: "Personal Information",
  },

  lastName: {
    label: "Last Name",
    type: FIELD_TYPES.text,
    visible: true,
    required: true,
    originalLabel: "Last Name",
    validation: (value) =>
      value.length >= 2 ? null : "Last name must be at least 2 characters",
    helpText: "Enter your legal last name as it appears on official documents",
    category: "Personal Information",
  },

  email: {
    label: "Email Address",
    type: FIELD_TYPES.email,
    visible: true,
    required: true,
    originalLabel: "Email Address",
    validation: (value) =>
      /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value) ? null : "Invalid email format",
    helpText: "We'll use this email for all course-related communications",
    category: "Contact Information",
  },
  phone: {
    label: "Phone Number",
    type: FIELD_TYPES.tel,
    visible: true,
    required: true,
    originalLabel: "Phone Number",
    validation: (value) =>
      /^\+?[\d\s-]{10,}$/.test(value) ? null : "Invalid phone number",
    helpText: "Include country code for international numbers",
    category: "Contact Information",
  },
  dob: {
    label: "Date of Birth",
    type: FIELD_TYPES.date,
    visible: true,
    required: true,
    originalLabel: "Date of Birth",
    helpText:
      "Must be at least 18 years old to enroll or have parent or guardian's consent",
    category: "Personal Information",
  },
  gender: {
    label: "Gender",
    type: FIELD_TYPES.select,
    visible: true,
    required: true,
    originalLabel: "Gender",
    options: [
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
    ],
    helpText: "",
    category: "Personal Information",
  },
  middleName: {
    label: "Middle Name",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    originalLabel: "Middle Name",
    category: "Personal Information",
  },
  addressLine1: {
    label: "Address Line 1",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    originalLabel: "Address Line 1",
    category: "Contact Information",
  },
  addressLine2: {
    label: "Address Line 2",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    originalLabel: "Address Line 2",
    category: "Contact Information",
  },
  city: {
    label: "City",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    originalLabel: "City",
    category: "Contact Information",
  },
  stateProvince: {
    label: "State/Province",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    originalLabel: "State/Province",
    category: "Contact Information",
  },
  postalCode: {
    label: "Postal Code",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    originalLabel: "Postal Code",
    category: "Contact Information",
  },
  country: {
    label: "Country",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    originalLabel: "Country",
    category: "Contact Information",
  },
  emergencyContactName: {
    label: "Emergency Contact Name",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    originalLabel: "Emergency Contact Name",
    category: "Emergency Information",
  },
  emergencyContactPhone: {
    label: "Emergency Contact Phone",
    type: FIELD_TYPES.tel,
    visible: false,
    required: false,
    originalLabel: "Emergency Contact Phone",
    category: "Emergency Information",
  },
  education: {
    label: "Education Background",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    originalLabel: "Education Background",
    category: "Background Information",
  },
  occupation: {
    label: "Occupation",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    originalLabel: "Occupation",
    category: "Background Information",
  },
  company: {
    label: "Company/Organization",
    type: FIELD_TYPES.text,
    visible: false,
    required: false,
    originalLabel: "Company/Organization",
    category: "Background Information",
  },
  languages: {
    label: "Languages Spoken",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    originalLabel: "Languages Spoken",
    category: "Background Information",
  },
  additionalCourses: {
    label: "Additional Courses Interest",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    originalLabel: "Additional Courses Interest",
    category: "Course Information",
  },
  referral: {
    label: "How did you hear about us?",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    originalLabel: "How did you hear about us?",
    category: "Course Information",
  },
  specialRequirements: {
    label: "Special Requirements",
    type: FIELD_TYPES.textarea,
    visible: false,
    required: false,
    originalLabel: "Special Requirements",
    category: "Course Information",
  },
};

export const STRUCTURAL_ELEMENTS = {
  header1: {
    label: "Section Header",
    type: FIELD_TYPES.header,
    visible: true,
    required: false,
    originalLabel: "Section Header",
    content: "New Section",
    variant: "h5",
    category: "Layout Elements",
  },
  textBlock1: {
    label: "Text Block",
    type: FIELD_TYPES.staticText,
    visible: true,
    required: false,
    originalLabel: "Text Block",
    content: "Enter your text here...",
    category: "Layout Elements",
  },
  divider1: {
    label: "Divider",
    type: FIELD_TYPES.divider,
    visible: true,
    required: false,
    originalLabel: "Divider",
    category: "Layout Elements",
  },
};
